version: "3"
services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    ports:
      - 80:80
    volumes:
      - ./project:/usr/src/app
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
